version: '3'
volumes:
  unuse:
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: testtest
      TZ: "Asia/Tokyo"
  web: &app_base
    env_file: .env
    image: ${WEB_IMAGE:-api_test/api_test:latest}
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    volumes:
      - .:/api_test
    environment:
      APP_DATABASE_USER: root
      APP_DATABASE_PASSWORD: testtest
      APP_DATABASE_HOST: db
      APP_DATABASE_NAME: api_test
      USERNAME: 'test'
    command: /bin/sh -c 'rm -f /costmgs/tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0'
  spring:
    <<: *app_base
    ports: []
    command: spring server
    stdin_open: true
    tty: true
    pid: host
    environment:
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:/api_test
      - ./spring:/tmp/spring
    environment:
      APP_DATABASE_USER: root
      APP_DATABASE_PASSWORD: testtest
      APP_DATABASE_HOST: db
      APP_DATABASE_NAME: api_test
